# Generated by Django 5.1 on 2024-08-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_makale_teslimtarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='teslimtarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Malzeme Teslim Tarihi'),
        ),
    ]
